# Generated by Django 2.0.7 on 2018-07-27 04:16

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(blank=True, default=0, verbose_name='порядок')),
                ('src', models.ImageField(upload_to='', verbose_name='изображение')),
            ],
            bases=(models.Model, main.models.UpdaterMixin),
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, default='', verbose_name='содержимое страницы')),
                ('region', models.CharField(blank=True, default='', max_length=70, verbose_name='регион')),
                ('district', models.CharField(blank=True, default='', max_length=70, verbose_name='район')),
                ('latitude', models.FloatField(null=True, verbose_name='широта')),
                ('longitude', models.FloatField(null=True, verbose_name='долгота')),
            ],
            bases=(models.Model, main.models.UpdaterMixin),
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='название вида')),
                ('info', models.TextField(blank=True, default='', verbose_name='общая информация')),
            ],
            bases=(models.Model, main.models.UpdaterMixin),
        ),
        migrations.AddField(
            model_name='record',
            name='species',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Species', verbose_name='вид'),
        ),
        migrations.AddField(
            model_name='image',
            name='record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Record', verbose_name='запись'),
        ),
    ]
