# Generated by Django 2.0.7 on 2018-09-19 04:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 9, 19, 4, 22, 20, 586451, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='page',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 9, 19, 4, 22, 26, 162562, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='page',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='photoalbum',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 9, 19, 4, 22, 35, 43033, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photoalbum',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='record',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 9, 19, 4, 22, 39, 290812, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='record',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='species',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 9, 19, 4, 22, 44, 522712, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='species',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
