# Generated by Django 2.0.7 on 2018-09-25 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20180919_0426'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='collection_date',
            field=models.DateField(blank=True, null=True, verbose_name='дата сбора'),
        ),
        migrations.AddField(
            model_name='record',
            name='collectors',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='собрал(и)'),
        ),
        migrations.AddField(
            model_name='record',
            name='forest_type',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='тип леса'),
        ),
        migrations.AddField(
            model_name='record',
            name='num',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='номер листа'),
        ),
        migrations.AddField(
            model_name='record',
            name='place',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='место сбора'),
        ),
        migrations.AddField(
            model_name='record',
            name='soil_type',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='тип почв'),
        ),
        migrations.AddField(
            model_name='record',
            name='source',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='место хранения листа'),
        ),
        migrations.AlterField(
            model_name='photoalbum',
            name='name',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='photoalbum',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='main.PhotoAlbum', verbose_name='родитель'),
        ),
        migrations.AlterField(
            model_name='photoalbum',
            name='slug',
            field=models.CharField(default='', max_length=20, verbose_name='идентификатор'),
        ),
        migrations.AlterField(
            model_name='record',
            name='content',
            field=models.TextField(blank=True, default=True, verbose_name='содержание'),
        ),
    ]
