# Generated by Django 2.0.7 on 2018-08-08 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20180803_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
