# Generated by Django 2.0.7 on 2018-09-26 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20180925_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='collection_date',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='дата сбора'),
        ),
    ]
