# Generated by Django 2.0.7 on 2018-08-10 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_page_public'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ('pk',), 'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображения'},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ('pk',), 'verbose_name': 'Страница', 'verbose_name_plural': 'Страницы'},
        ),
        migrations.AlterModelOptions(
            name='species',
            options={'ordering': ('pk',), 'verbose_name': 'Вид', 'verbose_name_plural': 'Виды'},
        ),
        migrations.AddField(
            model_name='page',
            name='slug',
            field=models.URLField(default='', verbose_name='путь'),
        ),
    ]
