# Generated by Django 2.0.7 on 2018-08-13 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20180810_0304'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='public',
            field=models.BooleanField(default=False, verbose_name='опубликовать'),
        ),
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='путь'),
        ),
        migrations.AlterField(
            model_name='record',
            name='latitude',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='широта'),
        ),
        migrations.AlterField(
            model_name='record',
            name='longitude',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='долгота'),
        ),
    ]
