# Generated by Django 2.0.7 on 2018-09-11 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20180911_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='main.Image'),
        ),
        migrations.AddField(
            model_name='image',
            name='category_name',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='image',
            name='category_slug',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
    ]
