# Generated by Django 2.0.7 on 2018-09-18 00:41

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20180911_2357'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoAlbum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(blank=True, default='', max_length=300)),
                ('child', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='main.PhotoAlbum')),
            ],
            bases=(models.Model, main.models.UpdaterMixin),
        ),
        migrations.RemoveField(
            model_name='image',
            name='category',
        ),
        migrations.RemoveField(
            model_name='image',
            name='category_name',
        ),
        migrations.RemoveField(
            model_name='image',
            name='category_slug',
        ),
    ]
