# Generated by Django 2.0.7 on 2018-09-18 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20180918_0106'),
    ]

    operations = [
        migrations.AddField(
            model_name='photoalbum',
            name='slug',
            field=models.CharField(default='', max_length=20),
        ),
    ]
